"use client";

/**
 * Interpretation panel — explains what the model is doing, using
 * numbers measured from the trajectories rather than a hand-written
 * table of what each layer "should" be doing.
 *
 * The layer profile (backend/examples/measure_layers.py) gives, per
 * layer: how strongly activation magnitude tracks next-token entropy,
 * how separable the self-check and think-block states are, and how
 * wide the layer's state space is. Those load-bearing measurements are
 * what this panel shows. Where the profile is missing we say so
 * rather than inventing a description.
 */

import { useApp } from "@/lib/store";
import { useEffect, useMemo, useState } from "react";

// ---------------------------------------------------------------------------
// Measured layer profiles. Generated by measure_layers.py; served as a
// static file next to the app. If it hasn't been generated yet, the
// panel degrades to showing only what it can measure live.
// ---------------------------------------------------------------------------

type LayerProfile = {
  layer: number;
  n_tokens: number;
  entropy_coupling: number;
  mean_norm: number;
  mean_entropy: number;
  effective_rank?: number;
  self_check_alignment?: number | null;
  think_alignment?: number | null;
  n_self_check?: number;
  n_think?: number;
};

type ProfileFile = {
  d_model: number;
  n_trajectories: number;
  source: string;
  layers: LayerProfile[];
};

function entropyToLabel(e: number | null | undefined): string {
  if (e == null) return "—";
  if (e < 0.5) return "Very confident";
  if (e < 1.0) return "Confident";
  if (e < 1.5) return "Moderate";
  if (e < 2.5) return "Uncertain";
  return "Very uncertain";
}

function entropyToColor(e: number | null | undefined): string {
  if (e == null) return "#888";
  if (e < 0.5) return "#22c55e";
  if (e < 1.0) return "#84cc16";
  if (e < 1.5) return "#eab308";
  if (e < 2.5) return "#f97316";
  return "#ef4444";
}

/** Colour a signed correlation by strength, not just sign. */
function couplingColor(r: number | null | undefined): string {
  if (r == null) return "#555";
  const a = Math.abs(r);
  if (a < 0.15) return "#4b5563";
  if (a < 0.3) return "#6366f1";
  if (a < 0.45) return "#8b5cf6";
  return "#c084fc";
}

function couplingLabel(r: number | null | undefined): string {
  if (r == null) return "unmeasured";
  const a = Math.abs(r);
  if (a < 0.15) return "no coupling";
  if (a < 0.3) return "weak";
  if (a < 0.45) return "moderate";
  if (a < 0.6) return "strong";
  return "very strong";
}

export default function InterpretationPanel() {
  const frames = useApp((s) => s.frames);
  const latest = useApp((s) => s.latest);
  const layer = useApp((s) => s.layer);

  const [profile, setProfile] = useState<ProfileFile | null>(null);
  const [profileState, setProfileState] = useState<"loading" | "ok" | "missing">(
    "loading"
  );

  useEffect(() => {
    let cancelled = false;
    fetch("/layer_profiles.json")
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(String(r.status)))))
      .then((j: ProfileFile) => {
        if (cancelled) return;
        setProfile(j);
        setProfileState("ok");
      })
      .catch(() => {
        if (!cancelled) setProfileState("missing");
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const layerProfile = useMemo(
    () => profile?.layers.find((p) => p.layer === layer) ?? null,
    [profile, layer]
  );

  // Where in the model does confidence actually live? This replaces
  // the old guess that layer 12 was "semantic".
  const confidencePeaks = useMemo(() => {
    if (!profile) return [];
    return [...profile.layers]
      .sort(
        (a, b) => Math.abs(b.entropy_coupling) - Math.abs(a.entropy_coupling)
      )
      .slice(0, 3);
  }, [profile]);

  const stats = useMemo(() => {
    if (frames.length < 3) return null;
    const v: number[] = [];
    for (let i = 1; i < frames.length; i++) {
      const a = frames[i - 1].point;
      const b = frames[i].point;
      v.push(Math.hypot(b.x - a.x, b.y - a.y, b.z - a.z));
    }
    const avg = v.reduce((a, b) => a + b, 0) / v.length;
    const reversals = frames.filter((f) => f.is_revisit).length;
    const selfChecks = frames.filter((f) => f.is_self_check).length;
    return {
      totalLength: v.reduce((a, b) => a + b, 0),
      avgSpeed: avg,
      reversals,
      selfChecks,
    };
  }, [frames]);

  return (
    <div className="flex flex-col gap-3 p-4 rounded-lg bg-panel border border-border">
      <h2 className="text-sm font-semibold text-gray-300 uppercase tracking-wider">
        Interpretation
      </h2>

      {/* --- current token --- */}
      <div className="rounded bg-bg/50 border border-border p-3">
        <div className="text-[10px] text-gray-500 uppercase tracking-wider mb-1.5">
          Current token
        </div>
        {latest ? (
          <>
            <div className="flex items-center gap-2 mb-2">
              <span className="text-sm font-mono text-yellow-300 truncate">
                {latest.token || "·"}
              </span>
              {latest.is_self_check && (
                <span className="px-1.5 py-0.5 rounded text-[10px] bg-orange-500/20 text-orange-300 shrink-0">
                  self-check
                </span>
              )}
            </div>
            <div className="text-[11px] space-y-0.5">
              <Row k="confidence" v={entropyToLabel(latest.entropy)} c={entropyToColor(latest.entropy)} />
              <Row k="perplexity" v={latest.perplexity?.toFixed(2) ?? "—"} />
              <Row k="entropy" v={latest.entropy?.toFixed(3) ?? "—"} />
            </div>
          </>
        ) : (
          <p className="text-[11px] text-gray-500">waiting for first frame…</p>
        )}
      </div>

      {/* --- measured layer profile --- */}
      <div className="rounded bg-bg/50 border border-border p-3">
        <div className="flex items-baseline justify-between mb-2">
          <span className="text-[10px] text-gray-500 uppercase tracking-wider">
            Layer {layer} — measured
          </span>
          {profileState === "missing" && (
            <span className="text-[9px] text-amber-600">no profile</span>
          )}
        </div>

        {layerProfile ? (
          <div className="text-[11px] space-y-1.5">
            <div>
              <div className="flex justify-between items-baseline">
                <span className="text-gray-500">‖h‖ ↔ entropy</span>
                <span
                  className="font-mono font-medium"
                  style={{ color: couplingColor(layerProfile.entropy_coupling) }}
                >
                  r={layerProfile.entropy_coupling >= 0 ? "+" : ""}
                  {layerProfile.entropy_coupling.toFixed(3)}
                </span>
              </div>
              <div className="text-[10px] text-gray-500">
                {couplingLabel(layerProfile.entropy_coupling)} —{" "}
                {layerProfile.entropy_coupling > 0.15
                  ? "bigger states go with more uncertainty here"
                  : layerProfile.entropy_coupling < -0.15
                  ? "bigger states go with more confidence here"
                  : "this layer's magnitude says little about certainty"}
              </div>
            </div>

            {layerProfile.effective_rank != null && (
              <Row
                k="effective rank"
                v={`${layerProfile.effective_rank.toFixed(0)} / 128`}
              />
            )}

            {layerProfile.self_check_alignment != null && (
              <div>
                <Row
                  k="self-check separability"
                  v={`${layerProfile.self_check_alignment >= 0 ? "+" : ""}${layerProfile.self_check_alignment.toFixed(3)}`}
                />
                <div className="text-[10px] text-gray-500">
                  cos gap between self-check and ordinary states
                  {layerProfile.n_self_check != null &&
                    ` (${layerProfile.n_self_check} self-check tokens)`}
                </div>
              </div>
            )}

            {layerProfile.think_alignment != null && (
              <Row
                k="think-block separability"
                v={`${layerProfile.think_alignment >= 0 ? "+" : ""}${layerProfile.think_alignment.toFixed(3)}`}
              />
            )}
          </div>
        ) : profileState === "loading" ? (
          <p className="text-[11px] text-gray-500">loading profile…</p>
        ) : (
          <p className="text-[11px] text-gray-500 leading-relaxed">
            No measured profile for this layer. Generate one with{" "}
            <code className="text-[10px] text-gray-400">
              measure_layers.py
            </code>
            .
          </p>
        )}
      </div>

      {/* --- where confidence lives --- */}
      {confidencePeaks.length > 0 && (
        <div className="rounded bg-bg/50 border border-border p-3">
          <div className="text-[10px] text-gray-500 uppercase tracking-wider mb-2">
            Where confidence lives
          </div>
          <div className="space-y-1.5">
            {confidencePeaks.map((p) => {
              const w = Math.min(100, (Math.abs(p.entropy_coupling) / 0.6) * 100);
              return (
                <div key={p.layer}>
                  <div className="flex justify-between text-[11px]">
                    <span className="text-gray-400">L{p.layer}</span>
                    <span
                      className="font-mono"
                      style={{ color: couplingColor(p.entropy_coupling) }}
                    >
                      r={p.entropy_coupling >= 0 ? "+" : ""}
                      {p.entropy_coupling.toFixed(2)}
                    </span>
                  </div>
                  <div className="h-1 bg-gray-800 rounded mt-0.5 overflow-hidden">
                    <div
                      className="h-full rounded"
                      style={{
                        width: `${w}%`,
                        backgroundColor: couplingColor(p.entropy_coupling),
                      }}
                    />
                  </div>
                </div>
              );
            })}
          </div>
          <p className="text-[10px] text-gray-500 leading-relaxed mt-2">
            Layers whose activation magnitude tracks next-token entropy
            most closely. Measured over{" "}
            {profile?.n_trajectories ?? "?"} trajectories.
          </p>
        </div>
      )}

      {/* --- trajectory stats --- */}
      {stats && (
        <div className="rounded bg-bg/50 border border-border p-3">
          <div className="text-[10px] text-gray-500 uppercase tracking-wider mb-2">
            Trajectory
          </div>
          <div className="text-[11px] space-y-0.5">
            <Row k="path length" v={stats.totalLength.toFixed(2)} />
            <Row k="mean step" v={stats.avgSpeed.toFixed(4)} />
            <Row k="direction reversals" v={String(stats.reversals)} />
            <Row k="self-check tokens" v={String(stats.selfChecks)} />
          </div>
        </div>
      )}
    </div>
  );
}

function Row({ k, v, c }: { k: string; v: string; c?: string }) {
  return (
    <div className="flex justify-between">
      <span className="text-gray-500">{k}</span>
      <span className="font-mono" style={c ? { color: c } : undefined}>
        {v}
      </span>
    </div>
  );
}
