# R-6 重跑预登记（新批次，cap 8192）

> **本文件在数据生成完成之前写死。** 生成仍在进行中（`gen_b2`，60 题 × 2 模式，
> cap 8192），本文件写于首批 2 条轨迹产出、全量尚未完成之时。
> 之后只**追加修订记录**，不改原文；每次修订写明触发原因与取数时点。

## 0. 为什么要重跑

旧批次（cap 2048）的 R-6 结论是「**未观察到**符号相反」，但支撑它的样本极薄：
严格标签下 think 模式只有 **4 条 correct / 2 条 wrong**（R-27 口径）。
B 路扩样的目的就是把这一格从 4 拉到可检验的量级。

**本轮不重跑整个干预实验。** 旧批次 R-1..R-5、C-1..C-3 的数字不动、也不重判。
本轮只回答一个问题：

> 在样本量足够时，`+w` 注入在「答对」与「答错」的 think 轨迹上，
> 效应方向是否不同？

## 1. 判决规则（取数前写死，不得事后调整）

### P0 人群
只用**新批次**的 think 轨迹。旧批次（cap 2048）与新批次（cap 8192）
provenance 不同、截断形态不同，**不混池、不合并判**。
任何跨批次陈述必须显式标注批次。

### P1 标签
用 `strict_label.py` 的 R-27 规则：四类答案陈述按位置排序取**最后一条**，
`correct ⟺ stated 存在且 == gt`；无陈述记 `unlabeled`。
`unlabeled` 既不计入 correct 也不计入 wrong。

### P2 方向 w —— 两个来源，都要跑
- **P2a（主）**：`w_new`，在**新批次自己的动摇点 vs 随机负例**上重新训练，
  用与旧实验相同的 `train_direction(pos, tmap, seed=42)`。
  ⇒ 这是对「效应可复现」的检验。
- **P2b（迁移）**：旧批次训练出的 `w_old`，原样用到新批次。
  ⇒ 这是对「方向跨题可迁移」的检验。
- ⚠ **披露**：选 w 的做法是看了旧批次结果之后定的（知道它是批内训练的）。
  这个知情写在前面，不藏。

### P3 剂量阶梯
`rel ∈ {0.5, 1.0}`（按 `w·h` 的类间间距归一）。
旧实验用 `{0.25, 0.5, 1.0}`，本轮**减半到两档**以控算力。
代价写在下面 P6 的功效讨论里。

### P4 对照
随机方向**采一个**（seed=42），扫**全部**剂量 —— 与旧实验同约定
（方向与剂量不可分别随机）。

### P5 位置抽样
每条轨迹最多取 **6 个** marker 位置，按生成 token 的**十等分位**各取一个，
保证覆盖整条 CoT 而不是只取密集段。
注入在 `t−1`，读 `t`（沿用旧实验的 OFF=1）。

### P6 主判决
对每条轨迹先算一个数：它在抽到的位置上，`+w @ rel=1.0` 相对基线的
**Δlogit(marker 集合) 的均值**。
然后按 correct / wrong 两组做 **Mann–Whitney U，双侧，α = 0.05**。

同时报：
- 两组中位数与 Hodges–Lehmann 估计量
- 效应量 Cliff's delta
- 若 correct 组轨迹数 < **10**，判决一律记 **「样本不足，不构成结论」**，
  **不得**因为 p 值小就报显著，也**不得**因为 p 值大就报「无差异」。

### P7 两套口径并列
- **口径 A（主）**：仅 marker 位置。
- **口径 B**：全部抽样位置（含非 marker）。
- ⚠ **披露**：把 marker-only 设为**主口径**是看了旧批次 R-5 之后定的
  （旧口径 A 的头条数字 87% 来自非 marker 位置）。两个口径都报，
  但主口径是事先写死的，不允许事后换成对自己有利的那个。

### P8 特异性必须同时报
每组同时报 `the` 集合的 Δ 与**特异性比**
`|Δmarker| / |Δ the|`。旧批次口径 B 下这个比只有 **0.060**，
即方向**远不止**影响标记词。本轮若该比仍 < 0.5，
结论必须写成「比随机方向大 N 倍，但**不能说专门**影响标记词」。

### P9 装置牙齿自检
开跑前必须先用新批次的前 3 条轨迹跑一次符号基准，确认：
`+w` 使 marker 集合的 Δlogit **单调上升**、`−w` 单调下降、随机方向落在两者之间。
三项任一不成立 ⇒ 装置坏了，**先修装置再谈分组**，不得用分组结果解释装置故障。

## 2. 算力预算（以及为什么要减半剂量）

旧实验：38 位置 × 28 变体，长前缀逐变体全量前向，数小时量级。
本轮若照搬：`~50 条轨迹 × 6 位置 × (1 基线 + 2 剂量 × 3 方向 + 随机)` ≈ 1800 次前向，
远超可接受范围。

**计划中的加速**：注入点在 `t−1`、读取在 `t`，而 `t−1` 之前的所有状态与剂量无关 ⇒
把 `prefix[0 : t−1]` 的 KV cache **按案例算一次**，各变体只重跑 2 个位置。
这与旧实验的批量化等价性结论一致（`batch_equiv.py`：噪声底 4.339e-05）。

⚠ **这条加速本身要先验证等价**：在 3 条轨迹上对比
「逐变体全量前向」与「共享 cache + 2 位置」在同一变体上的 Δlogit，
差 > 5e-3 则放弃加速、按慢路径跑完。

## 3. 明确不做的事

1. 不重判旧批次的 R-1..R-5、C-1..C-3。
2. 不把新旧批次混池做统计检验。
3. 不因为本轮结果好看就把 R-24 里「不能说专门影响标记词」那条删掉。
4. 不引用「+1.29 / 49.2×」那个已被撤回的头条数字。
5. 不在拿到 `correct` 组的轨迹清单后再改抽样规则。

## 4. 触发修订的已知风险（先写下来）

1. **标签产出率可能低于 pilot**：pilot 3/3 有标签，但 n=3。
   若全量 think 的标签产出率 < 80%，P6 的 correct 组可能不足 10 条。
2. **GPU 被抢占**：共享卡上 OOM 会让采集脚本**静默跳过**整题。
   收尾必须核对「完成条数 == 期望条数」，少一条就要补跑。
3. **回填对齐闸门拒写**：若 `reject>0`，说明 gen 段与重算对不齐，
   坐标系统不可信，本轮**中止**并先查原因。

---

## 修订 1（生成进行中追加，取数时点：首批 22/120 轨迹完成时）

> P0–P9 的判决规则**一字未改**。本修订只记生成期发生的资源事实与停止规则。

### 生成期实测（与 §4 的风险对照）

| §4 预写的风险 | 实际 |
|---|---|
| 标签产出率可能低于 pilot（n=3 不可靠） | **未发生**。think 触顶 55%，但触顶轨迹仍写下答案陈述 |
| 共享卡 OOM 会静默跳过整题 | **未发生 OOM**（22 条 0 次），但换成另一种代价：**算力被抢** |
| think 触顶率 | pilot 说 33%，实测 **55%**（6/11）—— pilot 的 n=3 低估了 |

### 速率：慢了 3.4 倍，拆开来是两部分

| 因素 | 倍数 | 性质 |
|---|---|---|
| trace 真的更长（每对 4404 vs pilot 3158 token） | 1.39× | 实打实的工作量 |
| GPU 被他人作业抢占（0.227 vs 0.093 s/token） | 2.45× | 资源，非数据 |
| 合计 | **3.4×** | |

⇒ 实测 499 s/条、剩余 13.6 h。**抢占是主因**，已把生成从 CVD 5 迁到 CVD 7
（两张卡同为 RTX PRO 5000 Blackwell，**批内同质性未破**），并复用同一个
输出目录 `gen_b2` 以便采集脚本 SKIP 已完成的 22 条、不白跑。

### 停止规则（现在写死，取数前）

> **停止点 = jsonl 顺序里的前 30 题（60 条轨迹），与标签无关。**

按题号停、不按标签停，是为了不让「跑到多少 correct」反过来决定「取多少题」。

⚠ **披露**：选 30 这个数，是看过「think 旧标签答对率 45%（5/11）」之后定的。
用的是**资源参数**（正确率）而不是**判决变量**（Δlogit 组间差），但这仍然
是知情决策，写在这里。30 题按 45% 外推约 **13 条 correct / 17 条 wrong**，
刚够过 P6 的「correct 组 ≥ 10 条」。

**若跑到 30 题时 correct 组 < 10 条，按 P6 原样记「样本不足，不构成结论」**，
不得因 p 值不好看而放宽门槛，也不得事后改成 20 题或 40 题。

---

## 修订 2：§2 的 KV-cache 加速计划**作废**，改走朴素慢路径

> §2 原文保留不改。以下是它的实测判决。

### 实测（`kv_share_equiv.py`，同一条 pilot 轨迹、同两个 marker 位置、4 个剂量）

| 判据 | bfloat16 | **float32** |
|---|---|---|
| E1 快慢 logit 最大差 ≤ 5e-3 | 3.75e-01 **FAIL** | **7.44e-05 PASS** |
| E2 逐变体 argmax 一致 | PASS | PASS |
| E3 快路径更快（摊薄前缀后） | 0.2× **FAIL** | 0.5× **FAIL** |
| E4 α=0 空挂不改变读数 ≤ 1e-3 | 3.75e-01 **FAIL** | **5.05e-05 PASS** |

### 两条结论

**① bf16 下的「FAIL」是我的容差量纲错了，不是快路径错了。**
float32 下两路一致到 **7.4e-05**，说明 `prefix cache + 只重跑 2 个位置`
在数学与实现上都是对的。bf16 的相对精度是 2⁻⁸ ≈ 0.39%，
而 logit 量级到 ~100 时，0.39% 就是 **0.4 绝对** —— 与实测的 0.375 吻合。
拿 **5e-3 的绝对容差**去卡一个 bf16 模型，等于要求 float32 的精度。
⇒ E1/E4 的容差必须随计算精度定，**不是固定常数**。

**② E3 在两种精度下都 FAIL，加速本身有害。**
每个变体都要 `copy.deepcopy` 一份 1580 token 的 KV cache
（28 层 × K/V 全量复制），代价盖过省下的前向时间。
⇒ **§2 的加速计划作废，走朴素慢路径。**

### §2 里那个「跑不完」的估计是错的

慢路径实测 **0.04–0.15 s/变体**（t≈1600–4400）。
按 P5 每条轨迹 6 个位置、P3/P4 的 7 个变体算：

```
30 题 × 6 位置 × 7 变体 ≈ 1260 个变体 × 0.15 s ≈ 190 s
```

**约三分钟。** 原先写的「1800 次长前缀全量前向，超出可接受范围」不成立
——旧实验慢是因为它每步都导出全部 28 层 hidden_states，而本轮只需要
位置 t 的 logits。**照这个配置根本不需要加速。**

### 为此付出的一笔学费：两处选卡错误

1. `CVD 编号 ↔ 卡` 依赖 `CUDA_DEVICE_ORDER`。我早先那张实测表是在
   **不设**该变量（FASTEST_FIRST）下测的，而测试脚本设了 `PCI_BUS_ID`
   ⇒ 同一个「CVD 3」在两套排序下指向**不同的卡**，
   我因此把 fp32 测试放到了生成任务正在用的那张卡上，直接 OOM。
2. 更隐蔽的一条：`torch.cuda.device_count()` 一调用就**初始化 CUDA**，
   此后再改 `CUDA_VISIBLE_DEVICES` 对当前进程**无效**。

⇒ 修法：脚本用 `CUDA_VISIBLE_DEVICES=GPU-<uuid>` 直接按 **UUID** 指定卡，
不枚举、不猜编号（CUDA 原生支持 UUID 形式）。

---

## 修订 3：回填可省；think 模式存在**与标签相关的选择效应**；停止点回到 60 题

> P0–P9 的判决规则一字未改。本修订记两件新事实与一处停止点修订。

### 3.1 回填**不在**关键路径上，可以省掉

R-1 的映射要 P（prompt token 数），回填脚本会往 npz 写 `prompt_token_ids`，
看上去 P 只能从那儿拿。但采集器第 279–280 行自己就写了

```
enc = tokenizer(text, add_special_tokens=False);  extra["prompt_tokens"] = len
```

——**P 就在侧车里**，且是同一份分词结果；而注入那一轮自己跑全序列前向，
`prompt_hidden_states` 一次都没读过。

实测（`coord_check.py`，新批次 22 条）：

| 判据 | 结果 |
|---|---|
| C1 每条侧车都有 `extra.prompt_tokens` | **22/22** |
| C2 `add_special_tokens=False` 复算 token 数逐条相等 | **22/22** |
| C3 分词往返自洽（decode 回原串） | PASS |
| C4 marker 换算 `全序列 = P + g − 1` 与 R-1 一致 | **22/22** |

⇒ 省掉约 1 小时 GPU（回填）+ 27 GB npz 回传。
（若将来要把新批次送进 3D 视图，再回填；那与 R-6 无关。）

### 3.2 think 模式存在**与标签相关的选择效应** ← 本轮最重要的负面发现

| 模式 | n | 触顶 | 有标签 | correct | wrong | unlabeled |
|---|---|---|---|---|---|---|
| think | 11 | **55%** | 55% | 5 | **1** | 5 |
| no_think | 11 | 0% | **100%** | 2 | 9 | 0 |

**截顶的那 55% 全部 unlabeled；有标签的 45% 里 83% 是对的。**
⇒ 能打标签的子集**系统性偏向答对**。

这不是样本量不够，是**结构性**的：模型在没把握时才长篇挣扎，
长到撞 cap 就写不出答案 ⇒ 答错的轨迹恰好是最容易被丢掉的那批。
**在 cap 8192 下，think 模式的 correct/incorrect 对照建不起来，加多少题都一样。**

### 3.3 按 Q3/Q4 逐模式判决（不指定「主模式」，让规则自己判）

| 模式 | 可抽样位置 | 30 题外推 correct/wrong | Q3(wrong≥8) | P6(correct≥10) |
|---|---|---|---|---|
| think | 66 | 14 / **3** | **FAIL** | PASS |
| no_think | 41 | **5** / 25 | PASS | **FAIL** |

⇒ **30 题这个停止点，两种模式都答不了 P6**：think 缺 wrong，no_think 缺 correct。

### 3.4 停止点：30 → **60**（回到最初计划的全量）

30 是修订 1 里为省算力而设的**缩减**停止点；60 才是本轮原始计划的全量。

**为什么必须回到 60**：按 18% 的 no_think 正确率，60 题给 correct≈11、
wrong≈49，两个门槛同时过；30 题则 correct≈5，卡在 P6 的 10 之下。

⚠ **披露**：这个修订是在**看到分组规模之后**做的。
方向是「把样本做多、回到原计划」，**不是**降门槛、不是换口径、不是缩样本。
若回到 60 之后 no_think 的 correct 组仍 < 10，按 P6 原样记
「样本不足，不构成结论」，不再作任何调整。

### 3.5 两种模式都跑、都报，不由我指定谁是「主」

Q3/Q4 本来就是逐模式的门禁：think 若 wrong<8 就记「样本不足」，
no_think 若 correct≥10 就给出 P6 的判决。**我不替规则选模式。**
think 模式那条「选择效应」本身就是一个独立结论，要与 P6 并列写出。

---

## 修订 4：60 题是**数据天花板**；P6 两种模式都必然判「样本不足」；
##          据此**新增**一组不依赖标签供给的次级分析 S1–S3

> P0–P9 的判决规则一字未改。本修订记一个新事实、一处对 §3.4 的更正、
> 一组**次级**分析。取数时点：15/60 题（30 条轨迹）完成，
> **Δlogprob 一个都还没算**——R-6 注入实验尚未开跑。

### 4.1 §3.4 里那个「18% ⇒ 60 题给 correct≈11」是错的

§3.4 用的是 11 题时的 no_think 正确率 2/11 = 18%。15 题时重测：

| 模式 | n | correct | 正确率 | Wilson 95% | wrong | 错误率 |
|---|---|---|---|---|---|---|
| no_think | 15 | 2 | 13.3% | [3.7%, 37.9%] | 11 | 73.3% |
| think | 15 | 5 | 33.3% | [15.2%, 58.3%] | 1 | 6.7% |

13.3% ⇒ **60 题给 correct≈8**，不是 11；卡在 P6 的 10 之下。
§3.4 的结论「回到 60 就能过」**不成立**，在此更正。
（Wilson 区间宽到 37.9%，说明 11 题时的 18% 本来就是运气；
这是小样本速率估计不可靠的又一例。）

### 4.2 加样本这条路已经封死

§3.4 把「回到 60 题」当作补救方向，隐含假设是「再多跑一些题」。
本轮核过：

- 算力节点上 `data/` 只有 `aime25/`（30 题）与 `aime26/`（30 题）；
- 从算力节点 curl `https://huggingface.co/api/models/...` 返回 **000**
  ⇒ **拉不到新年份**（`huggingface_hub` 1.28.0 装着，但没网）。

⇒ **60 题是硬天花板**，P0 也不允许混用旧批次的题。
外推（`label_supply_projection.py`，点估计）：

| 目标题数 | no_think correct/wrong | think correct/wrong |
|---|---|---|
| 30 | 4 / 22 ❌ | 10 / 2 ❌ |
| **60（本轮停止点）** | **8** / 44 ❌ | 20 / **4** ❌ |
| 90 | 12 / 66 ✅ | 30 / 6 ❌ |
| 120 | 16 / 88 ✅ | 40 / 8 ✅ |

90/120 题都在天花板之外，**不可达**。

### 4.3 结论：P6 主判决将是「样本不足」，这是**符合预登记的结局**

no_think 差在 correct（8 vs 10，属抽样噪声量级）；
think 差在 wrong（4 vs 8，且 §3.2 已证是**结构性**的）。
按 P6 原样记「样本不足，不构成结论」，**不再作任何调整**——
不降门槛、不换口径、不缩样本、不换题。

⚠ 披露：这个结局在**开跑注入实验之前**就已可判定（只靠标签供给，
不靠 Δlogprob）。换句话说本轮 R-6 的 P6 部分**注定不出结论**，
继续跑 60 题的价值不在 P6，而在 S1–S3。

### 4.4 次级分析 S1–S3（**新增，此刻预登记**）

动机：P6 死在「标签供给」上，而标签只是 R-6 的**分组变量**，
不是机制本身。以下三项在设计上绕开它，且**与 Δlogprob 是否已算无关**——
本修订写下时，一个 Δlogprob 数字都还没产生，因此是真预登记。
**S1–S3 是次级分析，不替代 P6；P6 判「样本不足」时结论必须照写。**

**S1 剂量单调性（完全不用标签）**

- 对象：`mark_w+_1.0` 与 `mark_w+_0.5`，**同一条轨迹内配对**。
- 检验：Wilcoxon signed-rank 双侧；并要求 `median(Δ@1.0 − Δ@0.5) > 0`
  （方向必须与 w 训练方向一致，见 P9 符号基准）。
- α=0.05，两模式 Bonferroni 校正（0.025）。
- 回答的问题：「注入 w 后，marker 集合的概率质量真的被推高了吗？
  剂量翻倍效应是否更大？」——这不需要知道答案对错。

**S2 三组 Kruskal–Wallis（把 unlabeled 留作独立组）**

- 分组：`correct` / `wrong` / `unlabeled` **三组**，不再二分组。
- 这样最大的一批样本（15 题里 unlabeled 占 11 条）不再被丢弃。
- α=0.05，两模式 Bonferroni 校正。同时报三组的描述统计。
- 明确：S2 的 H 显著**不等于**「correct 与 wrong 不同」——
  它也可能只是 correct 与 unlabeled 不同。报告时必须给出组间两两比较。

**S3 特异性（P8 的推广，完全不用标签）**

- P8 的 `|Δmark| / |Δthe|` 本来就对所有轨迹算，**与标签无关**；
  明确它在 S1/S2 的口径下照跑，n 从「有标签的 ~19 条」扩大到「全部 ~60 条」。
- `< 0.5` 时结论里仍必须写「不能说专门影响标记词」（P8 未放宽）。

### 4.5 本修订没有放宽什么

P0–P9 一字未改；ALPHA=0.05、MIN_CORRECT=10、MIN_WRONG=8、
SPEC_FLOOR=0.5、rel 阶梯 {0.5, 1.0}、L20 注入层、7 个 marker id，
全部原样。S1–S3 是**新增**，不是 P6 的改写。

---

## 修订 5：修订 4 §4.3 的预测**被数据推翻**——think 模式过 P6 双门槛，
##          反而是 no_think 卡住。**不改任何门槛。**

> 取数时点：50/60 题（99 条轨迹）完成，生成仍在跑。
> **Δlogprob 一个都还没算**，本修订只涉及标签供给。
> P0–P9 一字未改；S1–S3 原样。

### 5.1 修订 4 预测「两种模式都注定判样本不足」，实测对 think 是错的

| | 修订 4 的依据（15 题） | 实测（50 题） |
|---|---|---|
| think correct | 5（33.3%） | **12（24.0%）** |
| think wrong | 1（6.7%） | **8（16.0%）** |
| no_think correct | 2（13.3%） | 5（10.2%） |
| no_think wrong | 11（73.3%） | 39（79.6%） |

修订 4 §4.2 外推 think 在 60 题给 wrong≈4，**实测 50 题就已经 8**。
按 P6（MIN_CORRECT=10 / MIN_WRONG=8）：

| 模式 | correct | wrong | P6 门槛 | 判定 |
|---|---|---|---|---|
| think | **12** | **8** | 10 / 8 | ✅ **两项都过，可以出判决** |
| no_think | **5** | 39 | 10 / 8 | ❌ correct 不足 → 「样本不足」 |

**被我写错的是 think 那一侧。** no_think correct 从 13.3% 掉到 10.2%，
只是「本来就不够」的方向上继续；think wrong 从 6.7% 涨到 16.0%，
**是我在 15 题上估少了一倍半。**

⚠ **披露**：修订 4 §4.3 写的「P6 注定不成立、继续跑 60 题的价值不在 P6」，
在写下的 12 小时后就被推翻。**这是「小样本速率估计不足以支撑结论」的一个实例，
而修订 4 自己引用的 Wilson 区间已经给出过警告**（think wrong 的 15 题
Wilson 95% 是 [1.2%, 29.8%]，横跨了一个数量级——我却按点估计下了断言）。

### 5.2 为什么错在 think：**R-27 散文抽取的价值随 n 累积**

think 触顶 39 条的标签来源：

| | 条数 |
|---|---|
| 有 `\boxed{}` | **1** |
| 无 boxed、但有散文答案陈述（R-27 救回） | **8** |
| 仍 unlabeled | 30 |

⇒ **若沿用旧口径（只认 `\boxed{}`），think 触顶轨迹贡献的 wrong 是 0 条。**
加上未触顶的 3 条，think 总 wrong = 3 < 8 ⇒ P6 判「样本不足」。

**是 R-26 发现「旧抽取器把真标签当噪声扔掉」+ R-27 改用四类陈述规则，
才使 think 模式在 P6 上可行。** n 越大，R-27 救回的比例越多
（n=15 时触顶几乎全军覆没，n=50 时 23% 的触顶轨迹有标签）。

### 5.3 选择效应**没有消失**，只是变弱

| think（n=50） | correct | wrong | unlabeled |
|---|---|---|---|
| 触顶（39） | 4 | 5 | 30 |
| 未触顶（11） | 8 | 3 | 0 |

未触顶组 correct 占 73%（8/11），全部有标签组 correct 占 60%（12/20）——
**偏倚仍在，但比 n=15 时的 83% vs 17% 温和得多。**

⇒ **P6 对 think 的判决是在一个「触顶轨迹只有 23% 能打标签」的子集上做的。**
判决必须与这条选择效应**并列写出**，不得只报 p 值。
S2（三组 Kruskal–Wallis，把 unlabeled 留作独立组）在此处不是补充，
而是**唯一能同时看见触顶子集的分析**，照原样必跑。

### 5.4 明确不做的事

- **不**因为 think 通过了就去凑 no_think 的 correct（5 条不够就是不够）。
- **不**降低 MIN_CORRECT / MIN_WRONG。
- **不**重新指定「主模式」——修订 3 §3.5 说「我不替规则选模式」；
  现在是 P6 这条规则自己判出 think 可判决、no_think 不可，我照样只执行它。
- S1–S3 原样照跑，不因 P6 结果调整。

### 5.5 一条方法论教训

**速率类外推在 n<20 时不能支撑「注定成立」或「注定不成立」的断言。**
修订 3 与修订 4 各做了一次这样的断言，两次都被后续数据修正
（修订 3 的「think 缺 wrong」被 R-27 修正，修订 4 的「think 注定不够」被 n=50 修正）。
正确写法是：**要么等 n 到位再断言，要么把断言写成带区间的形式**
（本该写「think wrong 在 60 题落在 [1.2%, 29.8%]×60 = [1, 18] 条，
无法判定」，而不是「≈4 条，不过」）。

---

## 修订 6：P5 的取样实现有**静默偏倚**——轨迹后 40% 被整体丢弃。
##          开跑前修正（Δlogprob 仍为零）

> 取数时点：50/60 题（99 条轨迹）。**P9 装置符号基准只跑过 --smoke，
> 全量变体一次都没跑过，Δlogprob 一个数都还没产生** ⇒ 本次修正合法。

### 6.1 缺陷

P5 写的是「每条最多 6 位置按十等分位取」。原实现：

```python
for b in sorted(buckets)[:MAX_POS_PER_TRAJ]:      # 前 6 个**非空**分位
    out.append(buckets[b][0])                    # 桶内第一个
```

「按十等分位」的本意是让位置**铺满整条轨迹**，而「取前 6 个非空分位」
在 10 个分位全非空时只取第 0–5 分位 ⇒ **轨迹后 40% 被整体丢弃**，
桶内再取第一个 ⇒ 同一个分位里又偏前。

**这类缺陷不报错、不崩、位置数照样是 6**，报告里看不出任何异常。

### 6.2 实测（99 条侧车）

| 模式 | 10 分位全非空的轨迹 | 轨迹覆盖度中位（旧） | 完全铺满轨迹（旧） | 完全铺满轨迹（新） |
|---|---|---|---|---|
| think | 38/50 | **56%** | **0/50** | **50/50** |
| no_think | 3/48 | 100% | 34/48 | 46/48 |

**旧实现从来没有一次铺满过任何一条 think 轨迹（0/50）。**
而 think 正是唯一能过 P6 的模式（修订 5）⇒ 若不修，R-6 的 think 结论
实际是「**轨迹前 60% 的 marker 上**如何如何」，却会照常写成通用结论。

对截顶轨迹尤其糟：think 触顶 78%，尾部（撞 cap 前那一段）
恰恰是模型挣扎最剧烈、标记词最可能出现的区域。

### 6.3 修法

1. 在**非空分位**上均匀取最多 6 个（`idx = round(i·(k-1)/(m-1))`），
   而不是「最靠前的 6 个非空分位」；
2. 桶内取**中位**元素而不是第一个。

不改 P5 的任何**数**：位置数上限仍是 6、分位仍是十等分、分层逻辑不变。

### 6.4 自检

新增 `sample_markers_selftest.py`，21 项全过，判据取数前写死：

- T1 **尾部覆盖**（够到最后一个非空分位）——旧实现在这条上红
- T2 位置数上限、去重、成员性、有序
- T3 非空分位 ≤ 6 时**全部**取到，不因上限丢分位
- T4 桶内取中位
- T5 退化输入（空 / 单点 / 全同分位 / n_tok=0 / 越界）不崩
- T6 **牙齿自检**：把旧实现塞回去，必须被 T1c 判红

⚠ T6 第一次跑时**红的其实是我的断言**：我写的判据是「前后半都有点」，
而旧实现取到分位 5，`d>=5` 恰好成立 ⇒ 抓不住它。
真正的性质是**够到尾部**（`max(decile)>=8`）。
⇒ **「旧实现必须变红」这件事本身也要对判据用脑子**，否则牙齿自检是自欺。

### 6.5 不做的事

不因此重跑任何已完成的判据（本轮没有Δlogprob 相关产物需要重算）；
不调整 P5 的位置数上限；不把修正当作「事后调整数据」——
它发生在任何 Δlogprob 产生之前，与结果完全无关。


---

## 修订 7：**撤回并重写**——训练位置差**一个 token**，不是 192。
##          我第一版修订 7 的诊断是错的，修法把问题改大了。

> 取数时点：120/120 轨迹采集完成；R-6 全量一次都没跑过，Δlogprob 仍为零。

### 7.0 撤回声明

本节先前的版本断言「训练位置离 marker 约 **192** 个 token（中位 P）」，
并据此把 `load_xy` 改成 `H[extra.prompt_tokens + t - 1]`。**那个诊断是错的。**

错因：我**没有验坐标系**就把侧车的 `extra.prompt_tokens` 当成了 npz 的索引偏移。
实测 npz 的 `hidden_states` **只含生成段**（长度 == `n_generated_tokens`），
里面根本没有 prompt 那一段。

⇒ 我的「修复」把采样点推到 108~914 token 之外的**无关文本**，
实测后果：`class_gap` 从 ~300 塌到 **9.3**、正负打分差从 0.29 归零、
注入尺度跟着塌 32×、P9 读数全部掉进 bf16 量化底噪（±0.25）。
**把问题改大了。** 该版诊断与据此产生的所有推断一并作废。

### 7.1 真实坐标系（`coord_triple_check.py`，24/24 条轨迹）

| 判据 | 结果 |
|---|---|
| C1 `len(hidden_states) == n_generated_tokens`（只含生成段） | **24/24** |
| C2 `len(pid)`（当场分词）== 侧车 `extra.prompt_tokens` | **24/24**，差值恒为 0 |
| C4 口径不一致的轨迹 | C1 **0** 条、C2 **0** 条 |

⇒ 注入侧**本来就是对的**：`ids = pid + gen`、`up = ids[:P+t]`，
注入下标（绝对）`P+t-1`，对应 npz 索引 **`t-1`**，正是 marker 的**预测位**。

### 7.2 真正的缺陷（量级远小于 7.0 的说法）

原 `load_xy` 取 `H[t]` —— marker **自己**那个位置的表征，
而装置注入的是 `h(t-1)`（预测位）。
⇒ **差一个 token。** 与 R-1 阶段「探针必须测 h(t-1) 而非 h(t)」是同一条。

不报错、不崩，`w` 照样训得出来（class_gap ~300），
只是与装置差一位 ⇒ P9 的 +w 不稳定。

### 7.3 修法与守卫

1. `load_xy` 取 **`H[t-1]`**（负例同样偏移 `t'-1`，不许只改正例）。
2. **新增坐标系守卫**：`len(hidden_states) != n_generated_tokens` 直接
   `raise ValueError`。这条才是能拦住「相对索引当绝对索引」的那一道——
   若哪天 npz 改为存全序列，下标必须重算，而不是静默错位 P 个 token。

`load_xy_pos_selftest.py`（10 项全过，判据跑前写死）：
L1 正例 == `t-1` / L2 负例同口径 / **L3 牙齿：`H[t]` 必被 L1 判红** /
**L4 坐标系守卫必须抛错** / L5 绝对下标减 P == npz 索引（两个基数指同一 token）。

### 7.4 仍然有效的部分

**P9 FAIL 这个观测本身没有被推翻**，但它的解释变了：

- 剂量扫描（判据 D1–D4）显示 no_think 正控 **5/5 剂量步全单调升**
  ⇒ 装置、剂量阶梯、小剂量都没问题；
- think 在最小剂量 0.02 处中位就 −0.25 ⇒ 按 D2 判「方向问题」。

修好那**一个 token** 之后 P9 是否转绿，是判定
「FAIL 源于这一位错位」还是「源于 `w` 的训练目标（位置判别）
与读数（token logit）本就不是一回事」的直接实验。
后者若成立，是**实质发现**而非缺陷，须照实报出，不得调剂量调到绿为止。

### 7.5 家族特征（比 7.0 更准）

「段内索引 vs 全序列索引」的混用，加上**没先验坐标系就动手改**。
本项目里已经栽了两次：R-1 的「位置差 133 token」、本节的「差一个 token」。

⇒ **动任何跨产物取数的下标之前，先跑一个只读形状/长度的坐标系核对**
（不加载大数组：`.npz` 用 `zipfile` + `numpy.lib.format` 读 `.npy` 头即可，
本节的三方核对正是这么做的，前两版脚本都因为加载 380 MB 数组而超时）。

---

## 修订 8：P9 **判定器自身**有饱和漏洞——「装置完全没动」也能判通过。
##          同时更正修订 7 §7.4 的一处错判。两条都只收紧、不放松。

### 8.0 触发

修订 7 说「修好那一个 token 之后 P9 是否转绿」。重跑（`r6_smoke_t1.log`，
`H[t-1]` 口径，`class_gap=172.418`）后我去看**逐条**读数，而不是只看总判决，
于是看见一件判决器本身没说清的事。

### 8.1 缺陷：旧 P9 的单调性断言是**饱和的**

旧 P9 判定只有两条：

```
w+@1.0 >= w+@0.5   且   w-@1.0 <= w-@0.5
```

实测读数（`r6_smoke_t1.json`，逐条）：

| 轨迹 | mode | w+@0.5 → w+@1.0 | w-@0.5 → w-@1.0 | rand@1.0 | 旧 P9 |
|---|---|---|---|---|---|
| `p00__no_think` | no_think | **0.0 → 0.0** | **−0.0 → −0.0** | −0.25 | **PASS** |
| `p00__think` | think | 0.0 → **−1.25** | −0.25 → −0.75 | −0.0 | FAIL |
| `p01__no_think` | no_think | **−0.25 → −0.75** | 0.25 → 0.25 | −0.75 | FAIL |

第一行的 `w+` 读数是 **0.0 → 0.0**：`0.0 >= 0.0` 成立。
也就是说**装置在这条轨迹上一点没动（效应恰好为 0），却因为「0 不小于 0」
而通过了「装置符号基准」**。同一条的 `rand` 方向读 −0.25，比 `w+` 还大。

这与本项目记录的「饱和断言对任何常量偏移都不敏感」是同一族：
上一处是 `p == 2/C(n,n1)` 顶在边界放过 `i+j+1` 的常量平移，
这一处是 `x >= 0` 在 x 恒为 0 时恒真。**旧 P9 的 PASS 不携带任何信息。**

### 8.2 修法：噪声地板取自基准里**已有的随机方向对照**

```
通过 = 剂量单调（w+ 升、w- 降） 且 |w±@rel_max| > |rand@rel_max|
```

- 不另设魔数：`rand` 对照本来就在 P9 基准里跑着，只是没被判定用上；
- 剂量阶梯（P3 的 `rel{0.5, 1.0}`）**一个字没动**——
  事后调剂量调到绿为止是本项目明令禁止的；
- **只能把 PASS 变成 FAIL，不能反过来**，故这是收紧不是放松。

按新判定，同一批读数是 **0/3**（旧判定 1/3，且那 1 条是空转）。

### 8.3 自检（`p9_verdict_selftest.py`，11/11）

**旧闸门被原样抄进同一个自检文件当参照**，并断言 T0b：
同一份实测读数，旧闸门 PASS、新闸门 FAIL。只测新闸门的话，
「它比旧的严」这句话没有人验。

| 项 | 性质 |
|---|---|
| T0a/b/c/d | 零响应判 FAIL；**且**旧闸门在同一数据上 PASS；原因点明「未超过随机方向」；饱和自查（剂量差确实为 0） |
| T1a/b | 干净正效应判 **PASS**（闸门可满足，不是永远红）；PASS 时不得给出失败原因 |
| T2/T3 | 非单调升、符号翻转，各判 FAIL |
| T4 | 效应与随机方向同量级 ⇒ FAIL |
| T5 | 三条里一条红则整体红 |
| T6 | **剂量阶梯仍是 `{0.5, 1.0}`**（防止有人为求绿改 rel） |

T1 是必需的：一个永远红的闸门和一个永远绿的闸门一样没用。

### 8.4 更正：修订 7 §7.4「失败只发生在 think 轨迹上」**是错的**

§7.4 写「剂量扫描显示 no_think 正控 5/5 剂量步全单调升」。
把 P9 的逐条读数摊开看，实测是 **3 条里 2 条 `up_mono=False`**，
其中 `p01__no_think` 是 **no_think**，读数 `−0.25 → −0.75`（剂量越大越负）。

⇒ 「think 失败、no_think 干净」这个二分**不成立于 P9 基准上**。
它在**剂量扫描**（`dose_sweep.json`，`gap=302.456`、`H[t]` 口径、每条 2–3 个位置）
上成立，两条 no_think 确实都单调。两次观测的差别是**同时**变了三样东西：

1. 训练口径 `H[t]` → `H[t-1]`；
2. 绝对剂量（`gap` 302 → 172，`rel=1.0` 时 α 从 302 变成 172）；
3. 位置选取（P9 取 `sample_markers(...)[0]` **一个**位置，扫描取 2–3 个）。

**本修订不宣称能归因到哪一样。** 要归因需要三样逐一固定，属后续实验。

### 8.5 P9 基准的构成是**副产品**，不是设计

`smoke_tids = sorted(metas) 里的前 3 条有 marker 者`。实测（`p9_scope_check.py`）：

```
排序前 6：p00_no_think, p00_think, p01_no_think, p01_think, p02_no_think, p02_think
smoke_tids = p00_no_think, p00_think, p01_no_think
  think 1 条、no_think 2 条
落在 train_tids（think 且 >=3 marker）内的：1/3
```

后果有三条，都是**仪器**的性质而非装置的性质：

1. **混合模式**：2 条 no_think + 1 条 think，一条 think 就能拖垮 `pos_ok`；
2. **样本内**：3 条里有 1 条就在 `w` 的训练轨迹上，其余 2 条不是——
   基准既不是纯样本内也不是纯样本外，**无法解释**；
3. **alphabetical 前 3** 与「哪种模式更能代表判决所用的分布」无关。

⇒ 记为**实质发现**：P9 作为**绝对闸门**（挡住整个 R-6）不可靠。
处置见 §8.7，不在本修订里改。

### 8.6 顺带修的第二个静默缺陷：标签覆盖**从不检查**

核对 `labels_dryrun.json` 时发现它只覆盖 **99/120** 条轨迹
（think 50 条、no_think 49 条；`counter` 自洽 17+47+35=99）。
而 `r6_rerun.py` 原来写的是：

```python
"label": lab.get(tid, {}).get("strict", "unlabeled"),
```

不在文件里的轨迹被**静默并进 `unlabeled`**。实测后果：
打印出来的分布是 `{correct 17, unlabeled 56, wrong 47}`——
看起来完全合理、零报错，而正确的 think 子集是 **13 correct**。
少掉的 1 个 correct 会直接改变 P6 的 `correct ≥ 10` 判定。

- **「标签文件里没有这条」与「文件里写了 `strict=unlabeled`」是两回事**，前者是数据缺口；
- 修法：缺的那条记 `MISSING`，不进任何统计组，覆盖率打印并写进产物 json；
- `r6_verdict.py` 的 S2 同样把 `MISSING` 往 `unlabeled` 里塞，一并修；
- 牙齿自检 `S8h`（自检 26/26）：造 `unlabeled` 全 0.0、`MISSING` 全 1000.0，
  断言 `unlabeled` 组 **n=9、中位 0.0**。
  旧实现下是 **n=18、中位 500.0** ⇒ 判红。钉的是「两组被合并」这件事本身，
  不是新加的键名——只钉键名的话改个名字又变恒绿。
- 修的是**判决链**，不影响 `w_t1.npy`：`train_tids` 根本不读标签
  （`r6_rerun.py` 收 `think 且 >=3 marker`，与 `label` 无关）。
- 最终标签 `labels_full60.json` 已推远端，覆盖核对 **120/120**。

### 8.7 本修订**没有**做的事

- 没有改剂量阶梯、没有改 α、没有改词表、没有挪 P6 门槛；
- 没有把 P9 改成「只跑 think」——那会把 1 条 FAIL 变 0 条，是**放松**；
- 没有下「装置坏了」的结论。`w` 的 unembedding 对齐度三方对照
  （`w_real` / `w_old` / `w_t1`）**尚未测完**，`w_t1` 仍在训练，
  归因待 §8.4 的控制实验与该测量一并完成后再写修订 9。

