#!/usr/bin/env python3
"""Write the viewer-side model registry from the analysis outputs.

Why a generator instead of hand-written JSON
--------------------------------------------
The orientation layer quotes numbers that differ per model: the width, how
many dimensions actually participate, how much of the movement survives as a
net logit change. Those came out of `analyse_spread.py` on real data. Typing
them into a JSON file by hand would put a second, unverified copy of a
measured result next to the original -- and the day one of them is updated
without the other, the page will confidently state a number that no longer
matches the data it is showing. So they are read from the analysis outputs.

Every number below therefore has a provenance, and running this twice on the
same inputs produces the same file. Run it from the repo root::

    python3 .cache/build_model_registry.py

Inputs (all produced earlier in the pipeline):
    .cache/analysis/spread_1p7b.json          retention / n_eff / top-k
    .cache/analysis/spread_0p6b.json
    .cache/analysis/divergence_logits_v2.json C4 random-direction baseline
    .cache/analysis/divergence_logits_0p6b.json
"""

from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
A = REPO / ".cache/analysis"

MODELS = [
    {
        "id": "1p7b",
        "label": "Qwen3-1.7B",
        "base": "data/",
        "spread": A / "spread_1p7b.json",
        "divergence": A / "divergence_logits_v2.json",
        "paired": A / "paired_v2",
    },
    {
        "id": "0p6b",
        "label": "Qwen3-0.6B",
        "base": "data06/",
        "spread": A / "spread_0p6b.json",
        "divergence": A / "divergence_logits_0p6b.json",
        "paired": A / "paired_0p6b",
    },
]


def pct(x, nd=1):
    return round(x * 100, nd)


def summarise(m):
    sp = json.loads(m["spread"].read_text())
    dv = json.loads(m["divergence"].read_text())
    cands = [c for p in sp["problems"] for c in p["candidates"].values()]
    if not cands:
        raise SystemExit(f"{m['id']}: spread 文件里没有候选词")
    width = sp["problems"][0]["width"]

    ret = [c["retention"] for c in cands]
    neff = [c["n_eff"] for c in cands]
    topu = [c["top_k_vs_uniform"] for c in cands]

    c4h = sum(p["controls"]["C4_random"]["hits"] for p in dv["problems"])
    c4n = sum(p["controls"]["C4_random"]["n"] for p in dv["problems"])
    pctile = [p["direction_null"]["percentile_won"] for p in dv["problems"]]

    # The common-prefix length is what the viewer shows as "共 N 步"; read it
    # from the data rather than restating it.
    ks = [json.loads(p.read_text())["paired"]["n_common_prefix"]
          for p in sorted(m["paired"].glob("pair_*.json"))]

    return {
        "id": m["id"],
        "label": m["label"],
        # Short label for the <select>. The full name plus the width is ~150px,
        # which is enough to wrap the header line and push the whole left column
        # past the viewport -- the column is already exactly viewport-height, so
        # one wrapped line is a 25px page-level scrollbar. The full name is in
        # the h1 right next to it; repeating it in the dropdown buys nothing.
        "short": m["label"].replace("Qwen3-", ""),
        "base": m["base"],
        "d_model": int(sp["problems"][0]["width"]),
        "n_layers": int(json.loads(
            (Path("frontend/public/latent") / m["base"] / "manifest.json"
             ).read_text())["n_layers"]),
        "n_pairs": len(ks),
        "common_prefix": ks,
        "retention_pct": [pct(min(ret)), pct(max(ret))],
        # Display strings, so the page never formats a number itself. It did,
        # and JS turned 0.0 into "0" while the document and the test both said
        # "0.0%" -- three renderings of one measured value, and the one the
        # reader sees was the odd one out.
        "retention_text": f"{pct(min(ret)):.1f}%–{pct(max(ret)):.1f}%",
        "n_eff": [int(round(min(neff))), int(round(max(neff)))],
        "n_eff_text": f"{int(round(min(neff)))}–{int(round(max(neff)))}",
        "n_eff_pct": [pct(min(neff) / width), pct(max(neff) / width)],
        "top20_vs_uniform": [round(min(topu), 1), round(max(topu), 1)],
        "c4_random_pct": pct(c4h / c4n),
        "c4_random_text": f"{c4h}/{c4n}（{pct(c4h / c4n):.1f}%）",
        "c4_random_counts": [c4h, c4n],
        "direction_percentiles": [round(x, 1) for x in pctile],
        "direction_beats_random": sum(1 for x in pctile if x >= 86),
    }


def main():
    out = [summarise(m) for m in MODELS]
    dst = REPO / "frontend/public/latent/models.json"
    dst.write_text(json.dumps({
        "schema": "model_registry_v1",
        "note": ("Generated by .cache/build_model_registry.py from "
                 "analyse_spread.py / analyse_divergence_logits.py outputs. "
                 "Do not hand-edit: these are measured numbers, and the page "
                 "quotes them as such."),
        "models": out,
    }, ensure_ascii=False, indent=1))
    for m in out:
        print(f"{m['label']}  d={m['d_model']}  L={m['n_layers']}  "
              f"n_eff={m['n_eff']}（{m['n_eff_pct'][0]}–{m['n_eff_pct'][1]}%）  "
              f"retention={m['retention_pct'][0]}–{m['retention_pct'][1]}%  "
              f"C4={m['c4_random_pct']}%  真方向胜出 {m['direction_beats_random']}/6")
    print(f"\nwrote {dst}")


if __name__ == "__main__":
    main()
